import os
import boto3
import pymongo
from dotenv import load_dotenv, find_dotenv
from pymongo import MongoClient
import json

load_dotenv(find_dotenv())

password = os.environ.get("MONGODB_PWD")
connection = f"mongodb+srv://toby:{password}@wayabroad.ytg2mkg.mongodb.net/?retryWrites=true&w=majority&appName=wayabroad"

client = MongoClient(connection)

# Get a reference to the MongoDB collection
db = client['universityDB']  # replace 'your_database_name' with the name of your database

# Get a reference to the universities collection
universities_collection = db['universities']


# Remove the english_track fields from all documents
universities_collection.update_many({}, {'$unset': {'english_track ': ""}})


# db = client['universityDB']  # replace 'yourDatabaseName' with the name of your database
# universities_collection = db['universities']  # creates a new collection named 'universities'

# universities = [
#     {
#         "university_name": "Seoul National University",
#         "university_description": "Seoul National University (SNU) is one of South Korea's most prestigious universities, known for its rigorous academic programs and cutting-edge research. Situated in the heart of Seoul, SNU boasts a strong faculty and diverse student body, offering programs across various disciplines.",
#         "website": "https://en.snu.ac.kr/",
#         "ranking": 41,
#         "requirements": [
#             "Recommendation Letter(600 words)",
#             "TOPIK 3.0 or IELTS 6.0",
#             "SAT(Optional)",
#             "Extra Curricular activities"
#         ],
#         "korean_track": [
#             "College of Humanities: Korean Language and Literature",
#             "Chinese Language and Literature",
#             "English Language and Literature",
#             "French Language and Literature",
#             "German Language and Literature",
#             "Russian Language and Literature",
#             "Hispanic Language and Literature",
#             "Linguistics",
#             "Asian Languages and Civilizations",
#             "History",
#             "Archaeology and Art History",
#             "Philosophy",
#             "Religious Studies",
#             "Aesthetics",
#             "College of Social Sciences: Political Science and International Relations",
#             "Economics",
#             "Sociology",
#             "Anthropology",
#             "Psychology",
#             "Geography",
#             "Social Welfare",
#             "Communication",
#             "College of Natural Sciences: Mathematical Sciences",
#             "Statistics",
#             "Physics & Astronomy (Physics Major)",
#             "Physics & Astronomy (Astronomy Major)",
#             "Chemistry",
#             "Biological Sciences",
#             "Earth and Environmental Sciences",
#             "College of Nursing",
#             "College of Business Administration",
#             "College of Engineering: Civil and Environmental Engineering",
#             "Mechanical Engineering",
#             "Materials Science and Engineering. Electrical and Computer Engineering",
#             "Computer Science and Engineering",
#             "Chemical and Biological Engineering",
#             "Architecture and Architectural Engineering",
#             "Industrial Engineering",
#             "Energy Resources Engineering",
#             "Nuclear Engineering",
#             "Naval Architecture and Ocean Engineering",
#             "Aerospace Engineering",
#             "College of Agriculture and Life Sciences: Agricultural and Resource Economics",
#             "Regional Information",
#             "Crop Science and Biotechnology",
#             "Horticultural Science and Biotechnology",
#             "Vocational Education and Workforce Development",
#             "Forest Environmental Science",
#             "Environmental Materials Science",
#             "Food Science and Biotechnology",
#             "Animal Science and Biotechnology",
#             "Applied Life Chemistry",
#             "Applied Biology",
#             "Landscape Architecture",
#             "Rural Systems Engineering",
#             "Biosystems Engineering",
#             "Biomaterials Engineering",
#             "College of Fine Arts: Oriental Painting",
#             "Painting",
#             "Sculpture",
#             "Craft Design",
#             "College of Education:  Education Korean Language Education",
#             "English Language Education",
#             "German Language Education",
#             "French Language Education",
#             "Social Studies Education",
#             "History Education",
#             "Geography Education",
#             "Ethics Education",
#             "Mathematics Education",
#             "Physics Education",
#             "Chemistry Education",
#             "Biology Education",
#             "Earth Science Education",
#             "Physical Education",
#             "College of Human Ecology: Consumer and Child Studies (Consumer Science)",
#             "Consumer and Child Studies (Child Development and Family Studies)",
#             "Food and Nutrition",
#             "Fashion and Textiles",
#             "College of Veterinary Medicine",
#             "College of Music: Vocal Music",
#             "Composition",
#             "Music Piano",
#             "Orchestral instruments",
#             "Korean Music",
#             "College of Medicine",
#             "College of Liberal Studies"
#         ],
#         "english_track ": [
#             "Some classes are held in English please refer to each department`s website",
#         ],
#         "fall_intake": "03.04 - 03.07",
#         "spring_intake": "03.07 - 06.07",
#         "application_fee": "70,000 KRW",
#         "tuition_fee": "2,500,000-2,900.000 KRW per semester",
#         "application_link": "https://en.snu.ac.kr/admission/undergraduate/application"
#     },
#     {
#         "university_name": "KAIST ",
#         "university_description": "KAIST (Korea Advanced Institute of Science and Technology) is a leading research university globally recognized for its excellence in science, engineering, and technology. Located in Daejeon, KAIST fosters innovation and entrepreneurship, producing top-tier graduates and contributing significantly to advancements in science and technology.",
#         "website": "https://www.kaist.ac.kr/en/",
#         "ranking": 56,
#         "requirements": [
#             "IELTS 6.5  and SAT (nor required",
#             "but recommended)",
#             "Honors and Awards",
#             "Recommendation letter"
#         ],
#         "korean_track": [
#             "Not available"
#         ],
#         "english_track ": [
#             "College of Natural Sciences: Physics",
#             "Mathematical Sciences",
#             "Chemistry",
#             "College of Life Science & Bioengineering: Biological Sciences",
#             "Brain and Cognitive Sciences",
#             "College of Engineering: Mechanical Engineering",
#             "Aerospace Engineering",
#             "Electrical Engineering",
#             "Computer Science",
#             "Civil & Environmental Engineering",
#             "Bio & Brain Engineering",
#             "Industrial Design",
#             "Industrial & Systems Engineering",
#             "Chemical & Biomolecular Engineering",
#             "Materials Science & Engineering",
#             "Nuclear & Quantum Engineering",
#             "College of Business: Business and Technology Management"
#         ],
#         "fall_intake": "Early admission: 09.05 - 10.20; Regular admission: 11.07 - 01.12",
#         "spring_intake": "09.20 - 10.24",
#         "application_fee": "80,000 KRW",
#         "tuition_fee": "Full ride scholarship for all admitted students",
#         "application_link": "https://admission.kaist.ac.kr/intl-undergraduate"
#     },
#     {
#         "university_name": "Yonsei University (Underwood)",
#         "university_description": "Yonsei University, Underwood International College, is a renowned institution with a strong focus on international education and global perspectives. Situated in Seoul, it offers a wide range of undergraduate and graduate programs taught in English, attracting students from around the world to its vibrant campus.",
#         "website": "https://uic.yonsei.ac.kr/",
#         "ranking": 76,
#         "requirements": [
#             "IELTS 6.5 and SAT(Optional) and Extra Curricular activies",
#             "Interview"
#         ],
#         "korean_track": [
#             "Not available in UIC"
#         ],
#         "english_track ": [
#             "Underwood: Comparative Literature and Culture",
#             "Economics",
#             "International Studies",
#             "Political Science and International Relations",
#             "Life Science and Biotechnology",
#             "Humanities",
#             "Arts",
#             "and Social Sciences: Asian Studies",
#             "Information and Interaction Design",
#             "Creative Technology Management",
#             "Culture and Design Management",
#             "Justice and Civil Leadership",
#             "Quantitative Risk Management. Science",
#             "Technology",
#             "and Policy",
#             "Sustainable Development and Cooperation",
#             "Integrated Science and Engineering: Bio-Convergence",
#             "Energy and Environmental Science",
#             "and Engineering",
#             "Nano Science and Engineering"
#         ],
#         "fall_intake": "03.11 - 03.29",
#         "spring_intake": "Till 10.13",
#         "application_fee": "150,000 KRW",
#         "tuition_fee": "4,000,000-8,000,000 KRW",
#         "application_link": " https://univ.jinhakapply.com/Univ110805.aspx"
#     },
#     {
#         "university_name": "Korea University",
#         "university_description": "Korea University is a prestigious institution known for its comprehensive academic offerings and vibrant campus life. Located in Seoul, it emphasizes research, innovation, and global engagement, providing students with a dynamic learning environment and numerous opportunities for personal and professional growth.",
#         "website": "https://www.korea.edu/eng/",
#         "ranking": 79,
#         "requirements": [
#             "IELTS 6.0 or TOPIK 3.0"
#         ],
#         "korean_track": [
#             "College of Liberal Arts: Korean Language and Literature",
#             "Philosophy",
#             "Korean History",
#             "History",
#             "Sociology",
#             "Sinographic Literatures",
#             "English Language and Literature",
#             "German Language and Literature",
#             "French Language and Literature",
#             "Chinese Language and Literature",
#             "Russian Language and Literature",
#             "Japanese Language and Literature",
#             "Spanish Language and Literature",
#             "Linguistics",
#             "College of Life Sciences & Biotechnology:Life Sciences",
#             "Biotechnology",
#             "Food Bioscience and Technology",
#             "Environmental Science and Ecological Engineering",
#             "Food and Resource Economics",
#             "College of Political Science and Economics: Political Science and International Relations",
#             "Economics",
#             "Statistics",
#             "Public Administration",
#             "College of Science: Mathematics",
#             "Physics",
#             "Chemistry",
#             "Earth and Environmental Science",
#             "College of Engineering: Chemical & Biological Engineering",
#             "Materials Science & Engineering",
#             "Civil  ",
#             "Environmental",
#             "& Architectural Engineering",
#             "Architecture (5 years)",
#             "Mechanical Engineering",
#             "Industrial Management Engineering",
#             "Electrical Engineering",
#             "Integrative Energy Engineering",
#             "College of Education: Education",
#             "Korean Language Education",
#             "English Education",
#             "Geography Education",
#             "History Education",
#             "Home Economics Education",
#             "Mathematics Education",
#             "Physical Education",
#             "College of Informatics: Computer Science and Engineering",
#             "Data Science",
#             "College of Art & Design: Art & Design",
#             "College of Media & Communication: Media & Communication",
#             "College of Health Science: Biomedical Engineering",
#             "Biosystems & Biomedical Science",
#             "Health Environmental Science",
#             "Health Policy & Management",
#             "College of Interdisciplinary Studies:Interdisciplinary Studies",
#             "College of Smart Security: Smart Security",
#             "College of Psychology: Psychology"
#         ],
#         "english_track ": [
#             "College of International Studies: International Studies",
#             "Global Korean Studies"
#         ],
#         "fall_intake": "02.26 - 03.22",
#         "spring_intake": "August ",
#         "application_fee": "150,000 - 200,000 KRW",
#         "tuition_fee": "4,700,000-5,900,000 KRW",
#         "application_link": "https://oia.korea.ac.kr/oia/under/admission.do"
#     },
#     {
#         "university_name": "Sungkyunkwan University",
#         "university_description": "Sungkyunkwan University (SKKU) is one of South Korea's oldest and most prestigious universities, known for its rich history and academic excellence. With campuses in Seoul and Suwon, SKKU offers a wide range of programs spanning various fields, fostering a tradition of scholarship and leadership.",
#         "website": "https://www.skku.edu/eng/",
#         "ranking": 145,
#         "requirements": [
#             "IELTS 6.0 or TOPIK/Korean test "
#         ],
#         "korean_track": [
#             "Humanities: Confucian and Oriental Studies Korean Language and Literature",
#             "English Language and Literature",
#             "French Language and Literature",
#             "Chinese Language and Literature",
#             "German Language and Literature",
#             "Russian Language and Literature",
#             "Korean Literature in Classical Chinese",
#             "History",
#             "Philosophy",
#             "Library and Information Science",
#             "Social Sciences: Public Administration",
#             "Political Science and Diplomacy",
#             "Media and Communication",
#             "Sociology",
#             "Social Welfare",
#             "Psychology",
#             "Consumer Sciences",
#             "Child Psychology and Education Economics",
#             "Statistics",
#             "Business Administration",
#             "Film",
#             "Television and Multimedia",
#             "Fashion Design",
#             "Natural Sciences: Biological Sciences",
#             "Mathematics",
#             "Physics",
#             "Chemistry Food Science and Biotechnology",
#             "Bio-Mechatronic Engineering",
#             "Integrative Biotechnology",
#             "Engineering: Chemical Engineering/Polymer Science & Engineering",
#             "Advanced Materials Science and Engineering",
#             "Mechanical Engineering",
#             "Civil Architectural Engineering and Landscape Architecture",
#             "Systems Management Engineering",
#             "Nano Engineering",
#             "Electronic and Electrical Engineering",
#             "Sport Science"
#         ],
#         "english_track ": [
#             "Software "
#         ],
#         "fall_intake": "1- round: 02.26-03.08  2-round: 05.20-05.31",
#         "spring_intake": "1-round:  08.21 - 09.01;  2-round: 11.06 - 11.17",
#         "application_fee": "150,000 KRW",
#         "tuition_fee": "5,000,000 KRW - 7,800,000 KRW ",
#         "application_link": "https://admission-global.skku.edu/eng/index.html"
#     },
#     {
#         "university_name": "Hanyang University",
#         "university_description": "Hanyang University is a leading research university in South Korea, renowned for its strong emphasis on engineering, technology, and entrepreneurship. With campuses in Seoul and Ansan, Hanyang offers a dynamic learning environment and diverse opportunities for academic and extracurricular engagement.",
#         "website": "https://www.hanyang.ac.kr/web/eng",
#         "ranking": 164,
#         "requirements": [
#             "IELTS 6.0 or TOPIK 4.0",
#             "Interview"
#         ],
#         "korean_track": [
#             "Engineering: Architecture (5-year program)",
#             "Architectural Engineering (4-year program)",
#             "Civil and Environmental Engineering",
#             "Urban Planning and Engineering",
#             "Earth Resources and Environmental Engineering",
#             "Electronic Engineering",
#             "Computer Science",
#             "Information Systems",
#             "Electrical and Biomedical Engineering",
#             "Materials Science and Engineering",
#             "Chemical Engineering",
#             "Bioengineering",
#             "Organic and Nano Engineering",
#             "Energy Engineering",
#             "Mechanical Engineering",
#             "Nuclear Engineering",
#             "Industrial Engineering",
#             "Automotive Engineering",
#             "Data Science",
#             "Humanities: Korean Language & Literature",
#             "Chinese Language & Literature",
#             "English Language & Literature",
#             "German Language & Literature",
#             "History",
#             "Philosophy",
#             "Korean Language & Literature",
#             "English Language & Literature",
#             "Social Sciences: Political Science & International Studies",
#             "Sociology",
#             "Media Communication",
#             "Tourism",
#             "Natural Sciences: Mathematics",
#             "Physics",
#             "Chemistry",
#             "Life Science",
#             "Policy Science: Policy Studies",
#             "Public Administration",
#             "Economics&Finance: Economics & Finance",
#             "Business: Business Administration",
#             "Finance",
#             "Human Ecology: Clothing & Textiles",
#             "Food & Nutrition",
#             "Interior Architecture Design",
#             "Music: Voice",
#             "Composition",
#             "Piano",
#             "Orchestral Music",
#             "Korean Traditional Music",
#             "Performing Arts and Sports: Sport Industry and Science",
#             "Theater and Film",
#             "Dance",
#             "International Studies: Global Korean Studies"
#         ],
#         "english_track ": [
#             "International Studies: International Studies; Engineering: Data Science (english_track)"
#         ],
#         "fall_intake": "03.04-04.12",
#         "spring_intake": "09.01 - 10.11 ",
#         "application_fee": "142,000 KRW",
#         "tuition_fee": "4,700,000 - 7,000,000 KRW",
#         "application_link": "https://oia.hanyang.ac.kr/"
#     },
#     {
#         "university_name": "UNIST",
#         "university_description": "UNIST (Ulsan National Institute of Science and Technology) is a dynamic research university located in Ulsan, known for its innovative approach to education and interdisciplinary research. UNIST focuses on science and technology, aiming to address global challenges and produce leaders in various fields.",
#         "website": "https://www.unist.ac.kr/",
#         "ranking": 266,
#         "requirements": [
#             "IELTS or TOPIK (The minimum score is not specified by the admission)"
#         ],
#         "korean_track": [
#             "College of Engineering: Department of Mechanical Engineering",
#             "Department of Earth",
#             "Environment and Urban Construction Engineering",
#             "Department of New Materials Engineering",
#             "Department of Energy and Chemical Engineering",
#             "Department of Nuclear Engineering",
#             "Department of Semiconductor Engineering (Samsung Electronics Contract Department)",
#             "College of Information and Bio Convergence: Department of Design",
#             "Department of Biomedical Engineering",
#             "Department of Industrial Engineering",
#             "Department of Life Sciences",
#             "Department of Electrical and Electronic Engineering",
#             "College of Natural Sciences: Department of Physics",
#             "Department of Mathematical Sciences",
#             "Department of Chemistry",
#             "School of Business Administration"
#         ],
#         "english_track ": [
#             "College of Engineering: Department of Mechanical Engineering, Department of Urban and Environmental Engineering",
#             "Department of Materials Science and Engineering",
#             "School of Energy and Chemical Engineering",
#             "Department of Nuclear Engineering (english_track) ",
#             "College of Information and Biotechnology: Department of Design",
#             "Department of Biomedical Engineering",
#             "Department of Industrial Engineering",
#             "Department of Biological Sciences",
#             "Department of Electrical Engineering",
#             "Department of Computer Science and Engineering",
#             "College of Natural Sciences: Department of Physics",
#             "Department of Mathematical Sciences",
#             "Department of Chemistry",
#             "School of Business Administration"
#         ],
#         "fall_intake": "01.03 - 02.02",
#         "spring_intake": "Not available",
#         "application_fee": "55,000 KRW",
#         "tuition_fee": "Full ride scholarship for all admitted students",
#         "application_link": "https://admu-intl.unist.ac.kr/"
#     },
#     {
#         "university_name": "DGIST",
#         "university_description": "DGIST (Daegu Gyeongbuk Institute of Science and Technology) is a specialized research university located in Daegu, known for its excellence in science and technology. DGIST emphasizes interdisciplinary collaboration and innovation, attracting top talent from around the world to its state-of-the-art campus.",
#         "website": "https://www.dgist.ac.kr/en/html/sub03/030202.html",
#         "ranking": 307,
#         "requirements": [
#             "SAT",
#             "IELTS (The minimum score is not specified by the admission)and Recommendation (optional)"
#         ],
#         "korean_track": [
#             "Not available"
#         ],
#         "english_track ": [
#             "Physics",
#             "Chemistry",
#             "Life Sciences",
#             "Mechanical Engineering",
#             "Material Science and Engineering",
#             "Electronic Engineering",
#             "Computer Science and Engineering",
#             "Chemical Engineering"
#         ],
#         "fall_intake": "12.06-01.10",
#         "spring_intake": "Not available",
#         "application_fee": "0 KRW",
#         "tuition_fee": "Full ride scholarship for all admitted students",
#         "application_link": "https://www.dgist.ac.kr/iuadm/index.do;jsessionid=90A2854BDB0665D5B2DF5CEC9059FA87"
#     },
#     {
#         "university_name": "GIST",
#         "university_description": "GIST (Gwangju Institute of Science and Technology) is a leading research university in South Korea, specializing in science and technology education and research. Located in Gwangju, GIST fosters a culture of innovation and collaboration, contributing significantly to advancements in various scientific disciplines.",
#         "website": "https://www.gist.ac.kr/en/",
#         "ranking": 328,
#         "requirements": [
#             "IELTS (The minimum score is not specified by the admission)"
#         ],
#         "korean_track": [
#             "Not available"
#         ],
#         "english_track ": [
#             "Electrical Engineering and Computer Science",
#             "Materials Science and Engineering Mechanical Engineering",
#             "Earth Sciences and Environmental Engineering",
#             "Life Sciences",
#             "Physics",
#             "Chemistry"
#         ],
#         "fall_intake": "12.20-02.15",
#         "spring_intake": "Not available",
#         "application_fee": "0 KRW",
#         "tuition_fee": "Full ride scholarship for all admitted students",
#         "application_link": "https://www.gist.ac.kr/iuadm/"
#     },
#     {
#         "university_name": "Kyung Hee University",
#         "university_description": "Kyung Hee University is a prestigious institution known for its commitment to holistic education and global citizenship. With campuses in Seoul, Suwon, and Gwangneung, Kyung Hee offers a wide range of programs emphasizing creativity, humanism, and social responsibility.",
#         "website": "https://www.khu.ac.kr/eng/",
#         "ranking": 332,
#         "requirements": [
#             "IELTS 6.0 or TOPIK 3.0 and Interview"
#         ],
#         "korean_track": [
#             "College of Humanities: Department of Korean Language and Literature",
#             "Department of History",
#             "Department of Philosophy",
#             "Department of English Language and Linguistics",
#             "Department of Applied English Interpretation and Translation",
#             "College of Global Eminence: Department of Global Eminence",
#             "College of Politics and Economics: Department of Political Science",
#             "Department of Public Administration",
#             "Department of Sociology",
#             "Department of Economics",
#             "Department of International Business and Trade",
#             "Department of Media",
#             "College of Management: Department of Management",
#             "Department of Accounting and Taxation",
#             "College of Hotel and Tourism Management: Department of Hospitality Management",
#             "Department of Culinary Arts & Food Design Management",
#             "School of Tourism and Entertainment",
#             "Department of Hospitality Management",
#             "Department of Tourism",
#             "College of Human Ecology: Department of Child and Family Studies",
#             "Department of Housing and Interior Design",
#             "Department of Clothing and Textiles",
#             "Department of Food and Nutrition",
#             "College of Science: Department of Mathematics",
#             "Department of Physics",
#             "Department of Chemistry",
#             "Department of Biology",
#             "Department of Geography",
#             "Department of Information Display",
#             "College of Engineering: Department of Mechanical Engineering",
#             "Department of Industrial & Management Engineering",
#             "Department of Nuclear Engineering",
#             "Department of Chemical Engineering",
#             "Department of Advanced Materials Engineering for Information & Electronics",
#             "Department of Civil Engineering",
#             "Department of Architectural Engineering",
#             "Department of Environmental Science and Engineering",
#             "College of Electronics and Information: Department of Electronic Engineering",
#             "Department of Biomedical Engineering",
#             "College of Software Convergence: Department of Computer Engineering",
#             "Department of Software Convergence",
#             "Department of Artificial Intelligence",
#             "College of Applied Science: Department of Applied Mathematics",
#             "Department of Applied Physics",
#             "Department of Applied Chemistry",
#             "Department of Astronomy and Space Science",
#             "College of Life Sciences: Department of Genetics and Biotechnology",
#             "Department of Food Science & BIO Technology",
#             "Department of Oriental Medicine Biotechnology",
#             "Department of Plant & Environmental New Resources",
#             "Department of Smart-Farm Science",
#             "College of Foreign Language: Department of French",
#             "Department of Spanish",
#             "Department of Russian",
#             "Department of Chinese",
#             "Department of Japanese",
#             "Department of Korean",
#             "Department of Global Communication",
#             "College of Art and Design: Department of Industrial Design",
#             "Department of Visual Design",
#             "Department of Landscape Architecture",
#             "Department of Textile and Clothing Design",
#             "Department of Digital Contents",
#             "Department of Ceramics",
#             "Department of Postmodern Music",
#             "Department of Theater & Film",
#             "College of Physical Education: Department of Physical Education",
#             "Department of Sports Medicine",
#             "Department of Golf Industry",
#             "Department of Taekwondo",
#             "Department of Coaching"
#         ],
#         "english_track ": [
#             "Department of Management",
#             "Department of Global Hospitality & Tourism Management",
#             "Department of International Studies",
#             "Department of Global Korean Studies"
#         ],
#         "fall_intake": "1-round: 02.26-03.08; 2-round: 04.22-05.10",
#         "spring_intake": "Till 11.30",
#         "application_fee": "180,000 KRW",
#         "tuition_fee": "4,500,000-6,000,000 KRW",
#         "application_link": "https://iadmission.khu.ac.kr/gglobalcenter/user/contents/view.do?menuNo=8000031"
#     },
#     {
#         "university_name": "Sejong University",
#         "university_description": "Sejong University is a comprehensive institution located in Seoul, known for its strong academic programs and commitment to practical education. Sejong University offers a diverse range of undergraduate and graduate programs, preparing students for successful careers in various fields.",
#         "website": "https://www.sejong.ac.kr/eng.do",
#         "ranking": 436,
#         "requirements": [
#             "IELTS 5.5 or TOPIK 2.0 (Creative Studies",
#             "Arts and Physical Education majors)",
#             "TOPIK 4.0 (Korean Language and Literature,Media and Communication",
#             "Business Administration)",
#             "TOPIK 3.0 (Other majors)"
#         ],
#         "korean_track": [
#             "Liberal Arts: Korean Language and Literature",
#             "International Studies",
#             "History",
#             "Education",
#             "Social Sciences: Law",
#             "Business and Economics: Faculty of Business Administration",
#             "Hospitality and Tourism Management: Faculty of Hospitality,Tourism and Food Service Management",
#             "Faculty of Hospitality",
#             "Natural Sciences: Mathematics and Statistics",
#             "Faculty of Mathematics",
#             "Physics and Astronomy",
#             "Chemistry",
#             "Life Sciences: Faculty of Biological Systems",
#             "Integrative Biological Sciences and Industry",
#             "College of Convergence: Electrical Engineering",
#             "Semiconductor Systems Engineering",
#             "Computer and Information Security",
#             "Software",
#             "Artificial Intelligence and Robotics",
#             "Artificial Intelligence and Data Science",
#             "School of Intelligent Mechatronics Engineering",
#             "Creative Studies",
#             "Data Science",
#             "Artificial Intelligence",
#             "Engineering: Architectural Engineering",
#             "Architecture",
#             "Civil and Environmental Engineering",
#             "Environment",
#             "Energy & Geoinformatics",
#             "Energy Resources and Geosystems Engineering",
#             "School of Aerospace and Drone Engineering",
#             "Faculty of Mechanical and Aerospace Engineering",
#             "Nano Technology and Advanced Materials Engineering",
#             "Quantum and Nuclear Engineering",
#             "Education: Painting",
#             "Physical Education",
#             "Dance",
#             "Film Art"
#         ],
#         "english_track ": [
#             "Division of Global Leadership",
#             "Public Administration",
#             "Media and Communication",
#             "Faculty of Business Administration",
#             "Economics",
#             "Faculty of Hospitality,Tourism and Food Service Management",
#             "Computer Science and Engineering",
#             "Fashion Design",
#             "Music"
#         ],
#         "fall_intake": "1-round: 03.05-03.18  2-round: 04.25-05.09  3-round: 06.13-06.20",
#         "spring_intake": "1-round: 09.13 - 10.05; 2-round: 10.31 - 11.23",
#         "application_fee": "192,000 KRW",
#         "tuition_fee": "4,500,000 - 6,000,000 KRW",
#         "application_link": "https://sos.sejong.ac.kr/eng/admission/univ/index.do"
#     },
#     {
#         "university_name": "Chung Ang Univeristy",
#         "university_description": "Chung Ang University is one of South Korea's top universities, renowned for its academic excellence and vibrant campus culture. With campuses in Seoul and Anseong, Chung Ang offers a wide range of programs across disciplines, emphasizing creativity, innovation, and global perspectives.",
#         "website": "https://neweng.cau.ac.kr/",
#         "ranking": 494,
#         "requirements": [
#             "IELTS 5.5 or TOPIK 4.0 (No Korean - Korean course 6 months)"
#         ],
#         "korean_track": [
#             "Humanities: Korean Language & Literature",
#             "English Language & Literature",
#             "European Languages & Cultures",
#             "Asian Languages & Cultures",
#             "Philosophy",
#             "History",
#             "Social Sciences: Political Science",
#             "Public Administration",
#             "Psychology",
#             "Library & Information Science",
#             "Social Welfare",
#             "Media Communication",
#             "Sociology",
#             "Urban Planning and Real Estate",
#             "Business&Economics: Business Administration",
#             "Economics",
#             "Applied Statistics",
#             "Advertising & Public Relations",
#             "International Logistics",
#             "Natural Sciences: Physics",
#             "Chemistry",
#             "Biological Sciences",
#             "Mathematics",
#             "Biotechnology and Natural Resources: Bioresource & Bioscience",
#             "Food Science & Technology",
#             "Engineering: Civil & Environmental Engineering",
#             "Urban Design & Studies",
#             "Architecture & Building Science",
#             "Chemical Engineering & New Material Science",
#             "Mechanical Engineering ",
#             "ICT Engineering: Electrical and Electronics Engineering",
#             "Software",
#             "Arts: Performing Arts and Media",
#             "Design",
#             "Korean music",
#             "Global School of Arts",
#             "Sport: Sports Science"
#         ],
#         "english_track ": [
#             "Not available"
#         ],
#         "fall_intake": "03.22-04.19",
#         "spring_intake": "1-round: 09.06 - 09.27; 2-round: 11.13 - 11.24",
#         "application_fee": "180,000 KRW",
#         "tuition_fee": "4,600,000 - 7,000,000 KRW ",
#         "application_link": "https://oia.cau.ac.kr/bbs/board.php?tbl=bbs65&mode=VIEW&num=19&category=&findType=&findWord=&sort1=&sort2=&it_id=&shop_flag=&mobile_flag=&page=1"
#     },
#     {
#         "university_name": "Ewha Womans University",
#         "university_description": "Ewha Womans University is a prestigious women's university in Seoul, known for its long history of empowering women through education. Ewha offers a wide range of programs across disciplines, fostering a supportive environment for female students to excel academically and professionally.",
#         "website": "https://www.ewha.ac.kr/mbs/ewhaen/",
#         "ranking": 498,
#         "requirements": [
#             "IELTS 6.0",
#             "TOPIK is not required for korean_track"
#         ],
#         "korean_track": [
#             "College of Liberal Arts: Korean",
#             "Language & Literature Chinese",
#             "Language & Literature French",
#             "Language & Literature German",
#             "Language & Literature History",
#             "Philosophy Christian Studies",
#             "Division of English Language & Literature",
#             "College of Social Sciences: Political Science & International Relations",
#             "Public Administration",
#             "Economics",
#             "Library & Information Science",
#             "Sociology",
#             "Social Welfare",
#             "Psychology",
#             "Consumer Studies",
#             "Division of Communication & Media",
#             "College of Natural Sciences: Mathematics",
#             "Statistics",
#             "Physics",
#             "Division of Molecular Life and Chemical Science",
#             "College of Engineering: Division of Electronic and Semiconductor Engineering",
#             " Food Science and Biotechnology",
#             "Chemical Engineering and Materials Science",
#             "Architecture (5-year program)",
#             "Architectural and Urban Systems Engineering",
#             "Environmental Science and Engineering",
#             "Climate and Energy Systems Engineering",
#             "Mechanical and Biomedical Engineering",
#             "College of Music: Keyboard Instruments",
#             "Orchestral Instruments",
#             "Voice Composition",
#             "Korean Music",
#             "Dance",
#             "College of Art & Design: Division of Fine Arts",
#             "Division of Design",
#             "Division of Fiber & Fashion",
#             "College of Business Administration: Division of Business Administration",
#             "College of Science & Industry Convergence: Content Convergence",
#             "Fashion Industry",
#             "International Office Administration",
#             "Nutritional Science & Food Management",
#             "Health Convergence",
#             "Division of Kinesiology & Sports Studies",
#             "College of Artificial Intelligence: Computer Science and Engineering",
#             "Cyber Security"
#         ],
#         "english_track ": [
#             "Scranton College: Division of International Studies",
#             "Global Korean Studies (english_track)"
#         ],
#         "fall_intake": "03.07-04.11",
#         "spring_intake": "09.07 - 10.12",
#         "application_fee": "150,000 KRW",
#         "tuition_fee": "4,100,000 - 5,500,000 KRW",
#         "application_link": "http://isa.ewha.ac.kr/oisa/1442/subview.do"
#     },
#     {
#         "university_name": "Kyungpook National University",
#         "university_description": "Kyungpook National University (KNU) is one of South Korea's leading research universities, known for its strong emphasis on science, engineering, and medicine. With campuses in Daegu and Sangju, KNU offers a diverse range of programs and research opportunities, contributing to advancements in various fields.",
#         "website": "https://en.knu.ac.kr/",
#         "ranking": 520,
#         "requirements": [
#             "IELTS 5.5 or TOPIK 3.0"
#         ],
#         "korean_track": [
#             "Sangju Campus:",
#             "Ecology &Environmental Science: Plant Resources",
#             "Entomology",
#             "Animal Science",
#             "Forest Ecology and Protection",
#             "Horse/Companion and wild Animal Science",
#             "Animal Biotechnology Tourism",
#             "Kinesiology (Sport Studies)",
#             "Science &Technology: Construction and Disaster Prevention Engineering",
#             "Environmental and Safety Engineering",
#             "Precision Mechanical Engineering",
#             "Automotive Engineering",
#             "Nano & Advanced Materials Science and Engineering",
#             "Software",
#             "Energy Chemical Engineering",
#             "Food and Food Service Industry",
#             "Textile Fashion",
#             "Textile Fashion Design(Fashion Design)",
#             "Design (Textile Engineering)",
#             "Location-Based Information System",
#             "Smart Plant Engineering",
#             "Daegu Campus:",
#             "Humanities: Korean Language & Literature",
#             "English Language & Literature",
#             "History, Philosophy",
#             "French Language & Literature",
#             "German Language Literature",
#             "Chinese Language & Literature",
#             "Archaeology & Anthropology",
#             "Japanese Language & Literature",
#             "Korean Literature in Classical Literature Chinese",
#             "Russian Language & Literature",
#             "Social Sciences: Political Science & Diplomacy",
#             "Sociology",
#             "Library & Information Science",
#             "Geography",
#             "Psychology",
#             "Social Welfare",
#             "Media and Communication",
#             "Natural Sciences: Mathematics",
#             "Physics",
#             "Chemistry",
#             "Biotechnology",
#             "Earth System Science, Biology",
#             "Natural Sciences",
#             "Statistics",
#             "Economic&Business Administration: Business Administration",
#             "Economics & Trade",
#             "Engineering: Materials Science and Metallurgical Engineering",
#             "Advanced Materials Science and Engineering",
#             "Mechanical Engineering",
#             "Architecture(Architecture)",
#             "Architecture Engineering",
#             "Civil Engineering",
#             "Architecture (Architectural Engineering)",
#             "Applied Chemistry",
#             "Chemical Engineering",
#             "Polymer Science and Engineering",
#             "Textile System Engineering",
#             "Environmental Energy Engineering",
#             "IT Engineering: Electronics Engineering",
#             "Electronics Engineering(Artificial Intelligence)",
#             "Computer Science and Engineering (Platform Engineering Software & Data Science)",
#             "Computer Science and Engineering (Artificial Intelligence Computing)",
#             "Computer Science and Engineering (Global software convergence)",
#             "Computer Science and Engineering (Global Software Convergence)",
#             "Electrical Engineering",
#             "Agriculture and Life Sciences: Applied Bioscience",
#             "Plant Medicine",
#             "Food Science & Horticultural Sciences",
#             "Biotechnology",
#             "Agriculture & Life Sciences",
#             "Forest Sciences and Bio-fibers and Materials Science",
#             "Landscaper",
#             "Agricultural Civil Engineering",
#             "Smart Bio-Industrial Mechanical Engineering",
#             "Food and Resource Economics",
#             "Music and Arts: Korean Traditional Music",
#             "Teachers College: History Education",
#             "Human Ecology: Child Studies",
#             "Clothing and Textiles",
#             "Human Ecology",
#             "Food Science and Nutrition ",
#             "Public Administration: Public Administration"
#         ],
#         "english_track ": [
#             " International Studies Department"
#         ],
#         "fall_intake": "04.15-05.03",
#         "spring_intake": "10.17 - 11.04",
#         "application_fee": "80,000 KRW",
#         "tuition_fee": "1,900,000 - 2,500,000 KRW",
#         "application_link": "https://enter.jinhakapply.com/Notice/1015022/A"
#     },
#     {
#         "university_name": "Hankuk University of Foreign Studies",
#         "university_description": "Hankuk Foreign Studies University (HFSU) is a specialized institution in Seoul, renowned for its focus on foreign languages and international studies. HFSU offers comprehensive language programs and a vibrant international community, preparing students for successful careers in global contexts.",
#         "website": "https://www.hufs.ac.kr/",
#         "ranking": 575,
#         "requirements": [
#             "IELTS 5.5 or TOPIK 3.0"
#         ],
#         "korean_track": [
#             "Seoul Campus:",
#             "College of English: English Literature and Culture English for International Conferences and Communication (EICC)",
#             "College of Occidental Languages: Division of French Language",
#             "German",
#             "Russian",
#             "Spanish",
#             "Italian",
#             "Portuguese",
#             "Dutch",
#             "Scandinavian Languages",
#             "College of Asian Languages & Culture: Malay-Indonesian",
#             "Arabic",
#             "Thai",
#             "Vietnamese",
#             "Hindi",
#             "Turkish and Azerbaijani",
#             "Persian and Iranian Studies",
#             "Mongolian",
#             "College of Chinese: Chinese Language",
#             "Literature and Culture China Data Curation",
#             "Chinese Foreign Affairs and Commerce",
#             "College of Japanese: Japanese Language",
#             "Literature and Culture",
#             "Integrated Japanese Studies College of Social Science: Political Science and Diplomacy",
#             "Public Administration",
#             "Media Communication Division",
#             "College of Business and Economics: Economics",
#             "College of Business: Business Administration",
#             "College of Education: English Education",
#             "Korean Education French Education",
#             "German Education",
#             "Chinese Education",
#             "College of AI Convergence: Social Science & AI",
#             "Language & AI",
#             "Division of KFL: Korean Education as a Foreign Language",
#             "Korean Interpretation and Translation as a Foreign Language",
#             "Global Campus: ",
#             "College of Humanities: Department of Philosophy",
#             "Department of History",
#             "Department of Linguistics and Cognitive Science",
#             "College of Central and East European Studies: Polish",
#             "Romanian",
#             "Czech and Slovak Studies",
#             "Hungarian",
#             "South Slavic Studies Ukrainian Studies",
#             "College of International and Area Studies: Greek and Bulgarian Studies",
#             "Central Asian Studies",
#             "African Studies",
#             "Korean Studies College of Business and Economics: Global Business & Technology International Finance",
#             "College of Natural Science: Mathematics",
#             "Statistics",
#             "Electronic Physics",
#             "Environmental Science",
#             "Bioscience and Biotechnology",
#             "Chemistry",
#             "College of Engineering: Computer Engineering",
#             "Information Communications Engineering",
#             "Division of Semiconductor & Electronics Engineering",
#             "Industrial and Management Engineering",
#             "Ingenium College of Convergence Studies: Faculty of Convergence Studies",
#             "College of Culture & Technology: Division of Digital Contents",
#             "Division of Tourism & Wellness",
#             "Division of Global Sport Industry",
#             "College of AI Convergence: AI Data Convergence",
#             "Finance & AI Convergence",
#             "Division of Biomedical Engineering: Biomedical Engineering Studies",
#             "Global Open Major Division: Global Open Major Division",
#             "Division of Climate Changes: Climate Changes"
#         ],
#         "english_track ": [
#             "English Linguistics and Language Technology (ELLT)",
#             "International Studies"
#         ],
#         "fall_intake": "1-round: 03.04-03.22   2-round: 04.15-05.31 ",
#         "spring_intake": "Early Decision: 08.07 - 09.01; Regular Decision: 10.16 - 11.17",
#         "application_fee": "158,000 KRW",
#         "tuition_fee": "4,000,000 KRW - 5,200,000",
#         "application_link": "https://ipsi1.uwayapply.com/foreign/interhufs/?CHA=4"
#     },
#     {
#         "university_name": "Pusan National University",
#         "university_description": "Pusan National University (PNU) is a prominent research university located in Busan, known for its academic excellence and contributions to regional development. PNU offers a wide range of programs across disciplines, fostering innovation and collaboration to address societal challenges.",
#         "website": "https://www.pusan.ac.kr/english/Main.do",
#         "ranking": "   611-620",
#         "requirements": [
#             "IELTS 5.5 or TOPIK 3"
#         ],
#         "korean_track": [
#             "College of Humanities: Department of Korean Language and Literature",
#             "Department of Chinese Language and Literature",
#             "Department of Japanese Language and Literature",
#             "Department of English Language and Literature",
#             "Department of French Language and Literature",
#             "Department of German Language and Literature",
#             "Department of Russian Language and Literature",
#             "Department of Korean Literature in Chinese Characters",
#             "Department of Language and Information Department of History",
#             "Department of Philosophy",
#             "Department of Archaeology ",
#             "College of Social Sciences: Department of Public Administration",
#             "Department of Political Science and Diplomacy",
#             "Department of Social Welfare",
#             "Department of Sociology",
#             "Department of Psychology",
#             "Department of Library",
#             "Archive and Information Studies",
#             "Department of Media & Communication",
#             "College of Economics & International Trade: Department of International Trade",
#             "Department of Economics",
#             "Department of Tourism and Convention",
#             "Department of Public Policy & Management",
#             "School of Business: Department of Business Administration",
#             "College of Human Ecology: Department of Child Development and Family Studies",
#             "College of Natural Resources & Life Sciences: Department of Food and Resource Economics",
#             "College of Natural Sciences: Department of Mathematics",
#             "Department of Statistics",
#             "Department of Physics",
#             "Department of Chemistry",
#             "Department of Biological Sciences",
#             "Department of Microbiology",
#             "Department of Molecular Biology",
#             "Department of Geological Sciences",
#             "Department of Atmospheric Environmental Sciences",
#             "Department of Oceanography ",
#             "College of Engineering: School of Mechanical Engineering",
#             "Department of Polymer Science and Engineering",
#             "Department of Organic Material Science and Engineering",
#             "School of Chemical Biomolecular and Environmental Engineering (Environmental Engineering Major",
#             "Chemical and Biomolecular Engineering Major)",
#             "School of Materials Science and Engineering",
#             "School of Electrical and Electronics Engineering(Electrical Engineering Major)",
#             "School of Electrical and Electronics Engineering(Electronics Engineering Major)",
#             "School of Electrical and Electronics Engineering(Semiconductor Engineering Major)",
#             "Department of Architecture(5-year program)",
#             "Department of Architectural Engineering",
#             "Department of Urban Planning & Engineering",
#             "Department of Civil Engineering",
#             "Department of Aerospace Engineering",
#             "Department of Industrial Engineering",
#             "Department of Naval Architecture and Ocean Engineering",
#             "College of Nursing: Department of Nursing",
#             "College of Human Ecology: Department of Clothing and Textiles",
#             "Department of Food Science and Nutrition",
#             "Department of Interior & Environmental Design",
#             "College of Natural Resources & Life Sciences: Department of Plant Bioscience",
#             "Department of Horticultural Bioscience",
#             "Department of Animal Science",
#             "Department of Food Science & Technology",
#             "Department of Life Science & Environmental Biochemistry",
#             "Department of Biomaterial Science",
#             "Department of Bio-Industrial Machinery Engineering",
#             "Department of Applied Information Technology and Engineering",
#             "Department of Bioenvironmental Energy",
#             "Department of Landscape Architecture",
#             "College of Information and BioMedical Engineering: School of BioMedical Convergence Engineering",
#             "School of Computer Science and Engineering (Computer Engineering Major Artificial Intelligence Major)",
#             "College of Arts: Department of Music (Vocal Music Composition)",
#             "Department of Fine Arts (Carving & Modeling Korean Painting Western Painting)",
#             "Department of Plastic Arts (Wooden Furniture Painting Ceramics Textiles & Metal)",
#             "Department of Korean Music (String Vocal Wind Percussion Theory Composition)",
#             "Department of Dance (Korean Dance Ballet Modern Dance)",
#             "Department of Design (Visual Design Animation Design & Technology )",
#             "Department of Art Culture and Image"
#         ],
#         "english_track ": [
#             "Department of Global Studies(english_track)"
#         ],
#         "fall_intake": "03.08 - 03.26",
#         "spring_intake": "October",
#         "application_fee": "120,000 KRW",
#         "tuition_fee": " 1,800,000 - 2,900,000 KRW",
#         "application_link": "https://www.pusan.ac.kr/eng/CMS/Contents/Contents.do?mCode=MN013"
#     },
#     {
#         "university_name": "Ajou University",
#         "university_description": "Ajou University is a leading research institution in South Korea, known for its strong emphasis on engineering, technology, and internationalization. Situated in Suwon, Ajou offers a diverse range of programs and research opportunities, preparing students for global leadership roles.",
#         "website": "https://www.ajou.ac.kr/kr/eng.do",
#         "ranking": "   631-640",
#         "requirements": [
#             "IELTS 5.5 or TOPIK 3.0"
#         ],
#         "korean_track": [
#             "College of Engineering: Mechanical Engineering",
#             "Industrial Engineering",
#             "Chemical Engineering",
#             "Material Science and Engineering Applied Chemistry and Biological Engineering",
#             "College of Engineering",
#             "Environmental and Safety",
#             "Engineering Civil System Engineering",
#             "Transportation System Engineering",
#             "Architecture Engineering Major(4-years) Architecture(5 year)",
#             "College of Information Technology: Electrical and Computer Engineering",
#             "College of Computing and Informatics: Software and Computer Engineering",
#             "Cyber Security",
#             "Digital Media",
#             "College of Natural Sciences: Mathematics",
#             "Physics",
#             "Chemistry",
#             "Biological Science",
#             "College of Humanities: Korean Language and Literature",
#             "English Language and Literature",
#             "French Language Literature",
#             "History",
#             "Culture and Contents",
#             "College of Social Sciences: Economics",
#             "Public Administration",
#             "College of Social Sciences",
#             "Psychology",
#             "Sociology",
#             "Political Science and Diplomacy"
#         ],
#         "english_track ": [
#             "School of Business: Business Administration"
#         ],
#         "fall_intake": "03.25-04.17",
#         "spring_intake": "09.25 - 11.03",
#         "application_fee": "150,000 KRW",
#         "tuition_fee": "3,700,000 - 4,800,000 KRW",
#         "application_link": "https://enter.jinhakapply.com/Notice/1104046/A"
#     },
#     {
#         "university_name": "Inha University",
#         "university_description": "Inha University is a prestigious research institution located in Incheon, South Korea, renowned for its excellence in engineering, technology, and maritime studies. With a strong focus on practical education and industry collaboration, Inha offers a diverse range of programs preparing students for successful careers in various fields.",
#         "website": "https://www.inha.ac.kr/eng/",
#         "ranking": "   691-700",
#         "requirements": [
#             "IELTS 5.5 or TOPIK 3.0"
#         ],
#         "korean_track": [
#             "College of Engineering: Mechanical Engineering",
#             "Aerospace Engineering",
#             "Naval Architecture & Ocean Engineering",
#             "Industrial Engineering",
#             "Chemical Engineering",
#             "Polymer Science and Engineering",
#             "Materials Science Engineering",
#             "Civil Engineering",
#             "Environmental Engineering",
#             "Geo-informational Engineering",
#             "Faculty of Architecture, Energy Resources Engineering",
#             "Electrical Engineering",
#             "Electronic Engineering",
#             "Information and Communication Engineering",
#             "Department of Biological science: Biological Engineering",
#             "Biological Sciences",
#             "College of Software and Convergence: Computer Engineering",
#             "College of Natural Science: Mathematics",
#             "Statistics",
#             "Physics",
#             "Chemistry",
#             "Ocean Sciences",
#             "Food and Nutrition",
#             "College of Business Administration: Business Administration",
#             "Global Finance and Banking",
#             "Asia Pacific School of Logistics",
#             "International Trade",
#             "College of Social Science: Public Administration",
#             "Political Science and International Relations",
#             "Media Communication",
#             "Economics",
#             "Consumer Science",
#             "Child Studies",
#             "Social Welfare Studies",
#             "College of Humanities: Korean Language and Literature",
#             "History",
#             "Philosophy",
#             "China Studies",
#             "Japanese Language and Culture",
#             "English Language and Literature",
#             "French Language and Culture",
#             "Cultural Contents and Management",
#             "College of Medicine: Nursing",
#             " College of Education: Physical Education",
#             "College of Arts and Sports: Fine Arts",
#             "Design Convergence",
#             "Kinesiology",
#             "Theater and Film Studies",
#             "Fashion Design and Textiles"
#         ],
#         "english_track ": [
#             "School of Global Convergence Studies: International Business & Trade",
#             "Integrated System Engineering",
#             "Korean Language & Culture"
#         ],
#         "fall_intake": "04. 15 - 05. 24 ",
#         "spring_intake": "10.11 - 11.15",
#         "application_fee": "105,000 KRW",
#         "tuition_fee": "4,000,000 - 5,000,000 KRW",
#         "application_link": "https://internationalcenter.inha.ac.kr/internationalcenter/9985/subview.do"
#     },
#     {
#         "university_name": "Jeonbuk National University",
#         "university_description": "Jeonbuk National University (JNU) is a leading research university located in Jeonju, South Korea, known for its comprehensive academic programs and strong research infrastructure. JNU fosters innovation and creativity, offering a wide range of undergraduate and graduate programs across disciplines, contributing to regional development and global knowledge exchange.",
#         "website": "https://www.jbnu.ac.kr/eng/",
#         "ranking": "   721-730",
#         "requirements": [
#             "IELTS 5.5 or TOPIK 3.0"
#         ],
#         "korean_track": [
#             "University Headquarter: Smart Farm",
#             "Global Convergence College: Public Policy",
#             "Engineering: Architectural Engineering",
#             "Mechanical Engineering",
#             "Mechanical Design Engineering (Mechanical Design Engineering)",
#             "Mechanical Design Engineering (Nano-Bio Mechanical System Engineering)",
#             "Mechanical System Engineering",
#             "Urban Engineering",
#             "Biomedical Engineering",
#             "Industrial and Information Systems Engineering",
#             "Software Engineering",
#             "New Materials Engineering (Electronic materials Engineering)",
#             "Quantum System Engineering",
#             "Division of Convergence Technology Engineering (Major of IT Convergence Mechatronics Engineering)",
#             "Division of Convergence Technology",
#             "Engineering (Major of IT Applied System Engineering)",
#             "Computer Science",
#             "Engineering and Artificial Intelligence",
#             "Division of Civil/Environmental/Mineral Resources and Energy Engineering (Mineral Resources&Energy Engineering)",
#             "Division of Civil/Environmental/Mineral Resources and Energy Engineering (Civil Engineering)",
#             "Division of Civil/Environmental/Mineral Resources and Energy Engineering (Environmental Engineering)",
#             "Agriculture and Life Sciences: Division of Agricultural",
#             "Economics and Food Marketing (Food Marketing)",
#             "Division of Agricultural Economics and Food Marketing (Agricultural Economics)",
#             "Agricultural Biology",
#             "Animal Biotechnology",
#             "Wood Science and Technology",
#             "Forest Environment Science",
#             "Food Science and Technology",
#             "Horticulture",
#             "Crop Agriculture and Life Science",
#             "Landscape Architecture",
#             "Rural Construction Engineering",
#             "Education: English Education",
#             "Social Science: Social Welfare",
#             "Sociology",
#             "Media and Communication Studies",
#             "Psychology",
#             "Political Science & Diplomacy",
#             "Public Administration",
#             "Commerce: Business Administration",
#             "Economics",
#             "International Trade",
#             "Accounting",
#             "Human Ecology: Child Studies",
#             "Fashion Design",
#             "Housing Environmental Design",
#             "Arts: Dance (Ballet/Dance Education Creator)",
#             "Dance (Korea Folk Dance)",
#             "Dance (Contemporary Dance/Choreography)",
#             "Industrial Design (Product Design)",
#             "Industrial Design (Visual-Media Design)",
#             "Music(Composition)",
#             "Music(Voice)",
#             "Music(Piano)",
#             "Music(Wind Music)",
#             "Music(String)",
#             "Korean Music (Korean Traditional Theory/ Composition)",
#             "Korean Music (Vocal/Percussion Music)",
#             "Korean Music (Wind Music)",
#             "Korean Music (String Music)",
#             "Humanities: Archaeology and Cultural Anthropology",
#             "Korean Language & Literature",
#             "German Studies",
#             "Library and Information Science",
#             "Spanish & Latin american studies",
#             "English Language and Literature",
#             "Japanese Studies",
#             "Chinese Language & Literature",
#             "Philosophy",
#             "French African Studies",
#             "Natural Sciences: Science studies",
#             "Physics",
#             "Division of Life Sciences (Molecular Biology Major)",
#             "Division of Life Sciences (Life Sciences Major)",
#             "Sport Science",
#             "Earth & Environmental Sciences"
#         ],
#         "english_track ": [
#             "Global Convergence College: School of International Engineering and Science",
#             "The School of International Studies"
#         ],
#         "fall_intake": "1-round: 03.18-03.29 2-round: 05.01-05.15",
#         "spring_intake": "1-round: 09.18 - 09.29; 2-round: 11.01 - 11.15",
#         "application_fee": "80,000 KRW",
#         "tuition_fee": " 2,000,000 - 2,600,000 KRW",
#         "application_link": "https://ipsi5.uwayapply.com/foreign/jbnu/?CHA=4"
#     },
#     {
#         "university_name": "Konkuk University",
#         "university_description": "Konkuk University is a prominent institution in Seoul, South Korea, known for its dynamic academic programs and vibrant campus life. With a strong emphasis on innovation and entrepreneurship, Konkuk offers diverse opportunities for students to engage in research, internships, and international exchange, preparing them for success in the global marketplace.",
#         "website": "https://www.konkuk.ac.kr/eng.do",
#         "ranking": "   801-850",
#         "requirements": [
#             "TOPIK 3.0"
#         ],
#         "korean_track": [
#             "College of Art and Design: Department of Industrial Design",
#             "Department of Interior Design",
#             "Department of Fashion Design",
#             "Department of Visual Communication & Media Design",
#             "Department of Media Contents",
#             "Department of Formative Arts",
#             "College of Humanities and Social Sciences: Department of Business Administration",
#             "Department of Economics and Trade",
#             "Department of Police Science",
#             "Department of Fire and Disaster Prevention",
#             "Department of Library and Information Science",
#             "Department of Social Welfare",
#             "Department of Mass Communication",
#             "Department of Children's Literature and Korean Lang. & Lit.",
#             "Department of English Language and Culture",
#             "College of Science and Technology: Department of Mechatronics Engineering",
#             "Department of Computer Engineering",
#             "Department of Biomedical Engineering",
#             "Department of Green Technology Convergence",
#             "Department of Energy Materials Science & Engineering",
#             "College of Biomedical and Health Science: Department of Medicinal Biosciences",
#             "Department of Biotechnology",
#             "Department of Food and Nutrition Science",
#             "Department of Beauty Cosmetics",
#             "Department of Sport and Health Studies",
#             "Department of Golf Industry"
#         ],
#         "english_track ": [
#             "Not available"
#         ],
#         "fall_intake": "03.08-03.24",
#         "spring_intake": "10.10 - 10.30",
#         "application_fee": "187,000 KRW",
#         "tuition_fee": "3,000,000 - 3,500,000 KRW",
#         "application_link": "https://int.kku.ac.kr/noticeList.do?siteId=KUFUND&boardSeq=1495&menuSeq=6740"
#     },
#     {
#         "university_name": "Chonnam National University",
#         "university_description": "Chonnam National University (CNU) is a distinguished research institution located in Gwangju, South Korea, known for its commitment to academic excellence and social responsibility. With a focus on interdisciplinary collaboration and community engagement, CNU offers a wide range of programs addressing societal challenges and contributing to regional development.",
#         "website": "https://www.chonnam.ac.kr/en/",
#         "ranking": "   851-900",
#         "requirements": [
#             "IELTS 5.5 or TOPIK 3.0"
#         ],
#         "korean_track": [
#             "Gwang-ju Campus",
#             "AI Convergence: Artificial Intelligence",
#             "Intelligent Mobility  Nursing: Nursing",
#             "Business Administration: Business Administration",
#             "Economics",
#             "Engineering: School of Architecture",
#             "School of Architecture (Major of Architectural Engineering)",
#             "School of Architecture",
#             "Major of Architecture & Urban Design",
#             "School of Polymer Science Engineering",
#             "School of Mechanical Engineering",
#             "Department of Industrial Engineering",
#             "Department of Biotechnology & Bioengineering",
#             "School of Materials Science and Engineering",
#             "Department of Energy and Resources Engineering",
#             "Department of Electrical Engineering",
#             "School of Electronic and Computer Engineering",
#             "Department of Civil Engineering",
#             "School of Chemical Engineering",
#             "Agriculture and Life Sciences: Department of Agricultural Economics",
#             "Department of Agricultural & Biological Chemistry",
#             "Division of Animal Science",
#             "Department of Bioenergy Science and Technology",
#             "Department of Molecular Biotechnology",
#             "Department of Forest Resources",
#             "Department of Food Science & Technology",
#             "Department of Horticulture",
#             "Department of Convergence Biosystems Engineering",
#             "Department of Applied Biology",
#             "Department of Applied Plant Science",
#             "Department of Wood Science & Engineering",
#             "Department of Landscape Architecture",
#             "Department of Rural and Biosystems Engineering",
#             "Social Sciences: Department of Library and Information Science",
#             "Department of Cultural Anthropology and Archaeology",
#             "Media and Communication",
#             "Communication",
#             "Department of Sociology",
#             "Department of Psychology",
#             "Department of Political Science and Intemational Relations",
#             "Department of Geography",
#             "Department of Public Administration",
#             "Human Ecology: Department of Family Environment and Welfare",
#             "Division of Food and Nutrition",
#             "Department of Clothing and Textiles",
#             "Arts: Korean Traditional Music",
#             "Design",
#             "Fine Arts  Major of Korean Painting",
#             "Western Painting",
#             "Sculpture",
#             "Crafts Fine Arts",
#             "Theory of Arts",
#             "Music",
#             "Humanities: Korean Language & Literature",
#             "German Language & Literature",
#             "French Language & Literature",
#             "History",
#             "English Language & Literature",
#             "Japanese Language & Literature",
#             "Chinese Language & Literature",
#             "Philosophy",
#             "Natural Sciences: Physics",
#             "Biological Sciences and Technology",
#             "Biological Science & Technology - Major of Biological Science &Major of Systems Biology",
#             "Biology",
#             "Mathematics",
#             "Earth Systems & Environmental Science",
#             "Statistics",
#             "Chemistry",
#             "Yeo-su Campus",
#             "Engineering: Department of Architecture Design",
#             "Department of Mechanical Design Engineering",
#             "Department of Mechanical System Engineering",
#             "Department of Refrigeration & Air-conditioning Engineering",
#             "Department of Mechatronics Engineering",
#             "Department of Petrochemical Materials Engineering",
#             "Department of Integrative Biotechnology",
#             "Department of Biomedical Engineering",
#             "School of Electrical and Computer Engineering",
#             "School of Electrical and Computer Engineering - Major Electrical and Semiconductor Engineering",
#             "School of Electrical and Computer Engineering",
#             "Major in Computer Engineering",
#             "Department of Electronic Communication Engineering",
#             "School of Healthcare and Biomedical Engineering",
#             "Department of Chemical and Biomolecular Engineering Culture & Social Sciences: Department of English Studies",
#             "Department of Japanese Studies",
#             "Department of Chinese Studies",
#             "Division of Global Business",
#             "Department of Cultural Tourism Management",
#             "Department of Logistics and Transportation",
#             "Division of Culture Contents",
#             "Division of Culture Contents - Department of Multimedia / Electronic Commerce",
#             "Fisheries & Ocean Sciences: Department of Power System Engineering",
#             "Department of Aqualife Medicine",
#             "Department Smart Fisheries Resources Management",
#             "Department of Aquaculture",
#             "Department of Naval Architecture and Ocean Engineering",
#             "Department of Maritime Police Science",
#             "Department of Marine Bio food Science",
#             "Department of Marine Production Management",
#             "Department of Ocean Integrated Science"
#         ],
#         "english_track ": [
#             "Not available"
#         ],
#         "fall_intake": "1-round: 03.01-03.11;  2-round: 03.15-05.10",
#         "spring_intake": "1-round: 10.04 - 10.17;  2-round: 10.18 - 11.17",
#         "application_fee": "60,000 KRW",
#         "tuition_fee": "1,800,000 - 2,300,000 KRW",
#         "application_link": "https://ipsi5.uwayapply.com/foreign/jnu/?CHA=2"
#     },
#     {
#         "university_name": "Chungnam National University",
#         "university_description": "Chungnam National University (CNU) is a leading research university located in Daejeon, South Korea, renowned for its academic excellence and innovative research initiatives. With a strong emphasis on science, engineering, and technology, CNU fosters a culture of creativity and collaboration, producing top-tier graduates and contributing to advancements in various fields.",
#         "website": "https://eng.cnu.ac.kr/index.do",
#         "ranking": "   851-900",
#         "requirements": [
#             "IELTS 5.5 or TOPIK 3.0"
#         ],
#         "korean_track": [
#             "Humanities: Korean Language and Literature",
#             "English Language and Literature",
#             "German Language and Literature",
#             "French Language and Literature",
#             "Chinese Language and Literature",
#             "Japanese Language and Literature",
#             "Sino-Korean Literature",
#             "Linguistics",
#             "History",
#             "Korean History",
#             "Archaeology",
#             "Philosophy",
#             "Social Sciences: Sociology",
#             "Library and Information Science",
#             "Psychology",
#             "Communication",
#             "Social Welfare",
#             "Political Science and Diplomacy",
#             "Public Administration",
#             "Autonomy and Urban Administration",
#             "Economics and Management: Business Administration",
#             "International Trade",
#             "Agriculture and Life Sciences: Agricultural Economics",
#             "International Studies: International Studies",
#             "Natural Sciences: Mathematics",
#             "Information and Statistics",
#             "Physics",
#             "Astronomy and Space Science",
#             "Chemistry",
#             "Biochemistry",
#             "Marine Environmental Sciences",
#             "Geological Sciences",
#             "Engineering: Architecture(5-year program)",
#             "Civil Engineering",
#             "Mechanical Engineering",
#             "Aerospace Engineering",
#             "Materials Science and Engineering",
#             "Organic Materials Engineering",
#             "Chemical Engineering and Applied Chemistry",
#             "Electrical Engineering",
#             "Agriculture and Life Sciences: Crop Science",
#             "Horticultural Science",
#             "Environmental and Forest Resources",
#             "Biobased Materials",
#             "Applied Biology",
#             "Animal and Dairy Science",
#             "Agricultural and Rural Engineering",
#             "Biosystems Machinery Engineering",
#             "Food Science and Technology",
#             "Bio-Environmental Chemistry",
#             "Human Ecology: Clothing and Textiles",
#             "Consumer Science",
#             "Bioscience and Biotechnology: Biological Sciences",
#             "Microbiology and Molecular Biology",
#             "Art",
#             "Music and Physical Education: Dance(Korean dance)",
#             "Dance(modern dance) Dance(ballet)",
#             "Sport Science",
#             "Fine Art"
#         ],
#         "english_track ": [
#             "Not available"
#         ],
#         "fall_intake": "03.22-04.31",
#         "spring_intake": "11.13 - 12.01",
#         "application_fee": "60,000 KRW",
#         "tuition_fee": "1,800,000 - 2,500,000 KRW",
#         "application_link": "https://univ.jinhakapply.com/univ114080.aspx"
#     },
#     {
#         "university_name": "University of Seoul",
#         "university_description": "University of Seoul (UOS) is a prestigious institution located in the heart of Seoul, South Korea, known for its comprehensive academic programs and commitment to social justice and sustainability. With a diverse student body and strong faculty, UOS offers a wide range of programs across disciplines, preparing students to become global citizens and leaders in their respective fields.",
#         "website": "https://www.uos.ac.kr/eng",
#         "ranking": " 951-1000",
#         "requirements": [
#             "TOPIK 3.0"
#         ],
#         "korean_track": [
#             "Public Affairs and Economics: Public Administration",
#             "International Relations",
#             "Social Welfare",
#             "Economics",
#             "Science in Taxation",
#             "Business Administration: Business Administration",
#             "Engineering: Electrical and Computer Engineering",
#             "Chemical Engineering",
#             "Mechanical and Information Engineering",
#             "New Materials Science and Engineering",
#             "Civil Engineering",
#             "Computer Science and Engineering",
#             "Artificial Intelligence",
#             "Humanities: English Language and Literature",
#             "Korean Language and Literature",
#             "Korean History",
#             "Philosophy",
#             "Chinese Language and Culture",
#             "Natural Science: Mathematics",
#             "Statistics",
#             "Physics",
#             "Life Sciences",
#             "Environmental Horticulture",
#             "Applied Chemistry",
#             "Urban Science: Architecture (five-years)",
#             "Architectural Engineering",
#             "Urban Planning and Design",
#             "Transportation Engineering",
#             "Landscape Architecture",
#             "Urban Administration",
#             "Urban Sociology",
#             "Geoinformatics",
#             "Environmental Engineering",
#             "Arts and Physical Education: Music",
#             "Design",
#             "Sports Science",
#             "Environmental Sculpture"
#         ],
#         "english_track ": [
#             "Not available"
#         ],
#         "fall_intake": "03.15-03.24",
#         "spring_intake": "10.10 - 10.19",
#         "application_fee": "80,000 KRW",
#         "tuition_fee": "2,000,000 - 3,200,000 KRW",
#         "application_link": "https://oia.uos.ac.kr/iiceIntro/index.do?epTicket=LOG"
#     }
# ]


# for data in universities:
#     insert_result = universities_collection.insert_one(data)
#     if insert_result.acknowledged:
#         print(f"Data inserted with id: {insert_result.inserted_id}")




